name: .NET

on:
  pull_request:
    branches: [ prod ]

env:
  DOTNET_CONFIGURATION : Debug

jobs:

  build:

    runs-on: windows-latest
    permissions: write-all
    steps:

    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore palace.sln

    - name: Build Palace Client
      run: dotnet build src\Palace.Client\Palace.Client.csproj -c ${{env.DOTNET_CONFIGURATION}} --no-restore

    - name: Pack Palace Client
      run: dotnet pack --no-build --configuration ${{env.DOTNET_CONFIGURATION}} ${{github.workspace}}\src\Palace.Client\Palace.Client.csproj --output .

    # - name: Push Nuget Github
    #   run: dotnet nuget push *.nupkg --source https://nuget.pkg.github.com/dotnetpalace/index.json --api-key ${{secrets.NUGET_GITHUB}} --skip-duplicate

    - name: Push Nuget
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_GITHUB}} --skip-duplicate


    - name: Create Fake local AppSettings
      run: |
        mkdir ${{github.workspace}}\localconfig
        echo {} > ${{github.workspace}}\localconfig\appsettings.local.json

    - name: Build Palace Host
      run: dotnet publish src\palace.host\palace.host.csproj -c ${{env.DOTNET_CONFIGURATION}} --no-restore -v d

    - name: Zip Palace Host
      run: |
        cd ${{github.workspace}}\src\palace.host\bin\${{env.DOTNET_CONFIGURATION}}\net8.0\publish
        del appsettings.*.json
        7z.exe a -r -tzip ${{github.workspace}}\palacehost.zip * 

    - name: Build Palace Server
      run: |
        cd ${{github.workspace}}\src\palace.webapp
        dotnet publish -c ${{env.DOTNET_CONFIGURATION}}

    - name: Zip Palace WebApp
      run: |
        cd ${{github.workspace}}\src\palace.webapp\bin\${{env.DOTNET_CONFIGURATION}}\net8.0\publish
        del appsettings.*.json
        7z.exe a -r -tzip ${{github.workspace}}\palacewebapp.zip * 

    - name: Create empty appsettings local json
      run: |
        echo. > "src\PalaceDeployCli\appsettings.local.json"

    - name: Build Palace Deploy Cli
      run: dotnet publish src\PalaceDeployCli\PalaceDeployCli.csproj -c ${{env.DOTNET_CONFIGURATION}} --no-restore -v d

    - name: Zip Palace Deploy Cli
      run: |
        cd ${{github.workspace}}\src\PalaceDeployCli\bin\${{env.DOTNET_CONFIGURATION}}\net8.0\publish
        del appsettings.*.json
        7z.exe a -r -tzip ${{github.workspace}}\palacedeploycli.zip * 
        
    - uses: dev-drprasad/delete-tag-and-release@v1.0
      with:
        delete_release: false # default: false
        tag_name: Latest # tag name to delete
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with: 
        tag_name: Latest
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Palace
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{github.workspace}}\palacehost.zip
        asset_name: palacehost.zip
        asset_content_type: application/zip

    - name: Upload Release PalaceWeApp
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{github.workspace}}\palacewebapp.zip
        asset_name: palacewebapp.zip
        asset_content_type: application/zip

    - name: Upload Release PalaceDeployCli
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{github.workspace}}\palacedeploycli.zip
        asset_name: palacedeploycli.zip
        asset_content_type: application/zip
